Test: Install devbox bootstrap to ~/.local/bin; better error detection
Through some simple `sed` magic on the devbox first-stage bootstrap
between `curl` and `bash`, we change INSTALL_DIR and remove the sudo
invocation.

Also add the usual `trap ... 0` functionality to tell us if we don't
get to the end of the script.

diff --git a/Test b/Test
--- a/Test
+++ b/Test
@@ -1,14 +1,29 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
+PASSED=false
+trap '
+    ecode=$?
+    $PASSED || die $ecode "FAILURE: unexpected return code $ecode"
+' 0
+
 die() {
     local ecode="$1"; shift
     echo 1>&2 "ERROR:" "$@"
     exit $ecode
 }
 
-devbox version >/dev/null 2>&1 \
-    || curl -fsSL https://get.jetpack.io/devbox | bash
+if ! devbox version >/dev/null 2>&1; then
+    curl -fsSL https://get.jetpack.io/devbox \
+        | sed -e '
+            # "De-sudo" this, installing instead to ~/.local/bin/.rg
+            /INSTALL_DIR=/s,"/usr/local/bin,~/".local/bin,
+            s/ (requires sudo)//
+            s/$(command -v sudo || true) //
+        ' \
+        | bash
+fi
 devbox version >/dev/null || die 1 "Failed to run (install?) devbox."
 
+PASSED=true
 echo OK
